CONFIG_ZMK_KEYBOARD_NAME="minimal-keys"
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_SENSOR=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=20
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=8
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=8
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_BT_SMP_SC_PAIR_ONLY=n

CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=1600
CONFIG_PMW3610_X_SCALE=43
CONFIG_PMW3610_Y_SCALE=43
CONFIG_PMW3610_CPI_DIVIDOR=1
CONFIG_PMW3610_ORIENTATION_180=n
CONFIG_PMW3610_SCROLL_TICK=16
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_SCROLL_X=y
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=10
CONFIG_PMW3610_FORCE_AWAKE=y
CONFIG_PMW3610_POLLING_RATE_250=y
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700
CONFIG_PMW3610_SMART_ALGORITHM=n
CONFIG_PMW3610_ADJUSTABLE_MOUSESPEED=n
CONFIG_PMW3610_MOVEMENT_THRESHOLD=5
CONFIG_PMW3610_DEADZONE=4
CONFIG_PMW3610_DEADZONE_CLEAR=5
CONFIG_PMW3610_DEADZONE_TIMEOUT_MS=100
CONFIG_PMW3610_DEADZONE_CONSEC_FRAMES=2
CONFIG_PMW3610_DEADZONE_REMAINDER_CAP_X10=10
CONFIG_PMW3610_DEADZONE_ZONE_A_CONSEC=3
CONFIG_PMW3610_AXIS_LOCK_RATIO=0
CONFIG_FPU=y

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_BT_BAS=y

CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_TRANSPORT_BLE=y

CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y
CONFIG_ZMK_RUNTIME_HOLD_TAP=y
CONFIG_ZMK_RUNTIME_HOLD_TAP_STUDIO_RPC=y
